/**
 * Server-side type augmentations for Express Request.
 *
 * Import this file (or the middleware that uses it) to get the augmented
 * Express.Request type in scope throughout the server package.
 */

// Extend Express.Request with a per-request UUID set by requestIdMiddleware.
declare global {
  namespace Express {
    interface Request {
      /** UUID v4 generated by the requestId middleware. Present on every request. */
      requestId: string;
    }
  }
}

// This file has no runtime exports — it is imported solely for its side-effect
// of augmenting the global Express namespace.
export {};
