use_default_settings: true

general:
  debug: false
  instance_name: "WebPeel Search"

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "359bc3a474bd3540eb683ece978f46d5496ee3796c6e109c0c03230e0a9bc2c4"
  limiter: false
  public_instance: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

ui:
  static_use_hash: true

outgoing:
  request_timeout: 6
  max_request_timeout: 12
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
  - name: bing
    engine: bing
    shortcut: b
    disabled: false
  - name: brave
    engine: brave
    shortcut: br
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: false
  - name: mojeek
    engine: mojeek
    shortcut: mj
    disabled: false
  - name: qwant
    engine: qwant
    shortcut: qw
    disabled: false
